#!/usr/bin/env bash

usage() {
	echo "usage: $0 [options]"
	echo
	echo "-h    help"
	echo "-p    color palette"
	echo "-l    large color palette"
	echo "-m    main colors"
	echo "-c    color numbers"
}

palette() {
	local line=""
	for i in {0..7}; do
		line="$line$(tput setab $i)  "
	done
	echo "$line$(tput sgr0)"

	line=""
	for i in {8..15}; do
		line="$line$(tput setab $i)  "
	done
	echo "$line$(tput sgr0)"
}

largepalette() {
	local line=""
	for i in {0..7}; do
		line="$line$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line$(tput sgr0)"

	line=""
	for i in {8..15}; do
		line="$line$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line$(tput sgr0)"
}

main() {
	local line=""
	for i in {0..7}; do
		line="$line$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line$(tput sgr0)"
}

numbers() {
	local line=""
	local line2=""
	for i in {0..7}; do
		line="$line $i "
		line2="$line2$(tput setab $i)   "
	done
	echo "$line$(tput sgr0)"
	echo "$line2$(tput sgr0)"
	echo "$line2$(tput sgr0)"
}

case "$1" in
	-h)
		usage
		;;
	-p)
		palette
		;;
	-l)
		largepalette
		;;
	-m)
		main
		;;
	-n)
		numbers
		;;
	*)
		usage
		;;
esac
