#!/usr/bin/env bash

usage() {
	echo "usage: $0 [options]"
	echo
	echo "-h    help"
	echo "-a    all colors"
	echo "-p    primary colors"
	echo "-n    color numbers"
	echo
	echo "You can set colors with:"
	echo "foreground: $ tput setaf <number>"
	echo "background: $ tput setab <number>"
	echo "reset:      $ tput sgr0"
}

all() {
	local line=""
	for i in {0..7}; do
		line="$line$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line$(tput sgr0)"

	line=""
	for i in {8..15}; do
		line="$line$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line$(tput sgr0)"
}

primary() {
	local line=""
	for i in {0..7}; do
		line="$line$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line$(tput sgr0)"
}

numbers() {
	local line=""
	local line2=""
	for i in {0..7}; do
		line="$line  $i "
		line2="$line2$(tput setab $i)    "
	done
	echo "$line$(tput sgr0)"
	echo "$line2$(tput sgr0)"
	echo "$line2$(tput sgr0)"

	line=""
	line2=""
	for i in {8..9}; do
		line="$line  $i "
		line2="$line2$(tput setab $i)    "
	done
	for i in {10..15}; do
		line="$line $i "
		line2="$line2$(tput setab $i)    "
	done
	echo "$line2$(tput sgr0)"
	echo "$line2$(tput sgr0)"
	echo "$line$(tput sgr0)"
}

case "$1" in
	"")
		all
		;;
	-a)
		all
		;;
	-p)
		primary
		;;
	-n)
		numbers
		;;
	*)
		usage
		;;
esac
