#!/bin/env bash

t="abcd"

for i in {0..7}; do
	fg[$i]="\e[3${i}m"
	fg2[$i]="\e[1;3${i}m"
	bg[$i]="\e[4${i}m"
done

if [ "$1" = "-h" ]; then
	echo "$0 - Display terminal colors with escape sequences"
	echo
	echo "Usage: $0 [-v] [-h]"
	exit
elif [ "$1" = "-v" ]; then
	echo "       ${bg[@]}"
	for f in ${fg[@]} ${fg2[@]}; do
		echo -en "$f $t "
		for b in ${bg[@]}; do
			echo -en "$f $b $t \e[00m"
		done
		echo " $f"
	done
else
	echo "       ${bg[@]}"
	for f in ${fg[@]}; do
		echo -en "$f $t "
		for b in ${bg[@]}; do
			echo -en "$f $b $t \e[00m"
		done
		echo " $f"
	done
fi
