#!/bin/env bash

if [[ "$1" =~ ^[0-9]+$ ]] && [[ "$2" =~ ^[0-9]+$ ]]; then	
	max=$1
	count=$2
	shift 2
	for ((i=1; i <= max ; i++)); do
		sleep $count
		eval "$@"
	done
else
	echo "$0 - Repeat command"
	echo
	echo "Usage: $0 [count] [interval] [command]"
fi
